---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgCWamf78k0dpD/Q54SvKTzdkEiMtLpxfiypYh7RBY40FcFob8uGiVyzPy7rKr98I/GuBZKklL1bDhnQnnWgxkF3AOy2X9NmPDAqD1gPkIH9LpD8Ys9ui0aNbhWSB3uXKVvQOIEnYakx1yiayr8YhftYWBD6reKBGY6hd6Aczo0xqa40loTkvu0QKzSAuaw8rn/Q+s28wtA+wTwJKNADIVpm4ggxgjYMJvZ9Z9c8MtycURg2SaxUtT20raVpOcTmVuiLBBbTkpCo+HakAFcgC5UIasRL9CxXfuWu/DfbXKIfMMMXBDMvojbhnSvskpxtElkBwOE22M998TA7KvCyW6IoW2/qr6HbWWlPozZrZPUjt4cMWpD0ke8rytWPLY2uJgtx6UX4dauK203F3XXYnkQH5p8bI3bKF1jyI6TPUv1s6Ub2hi7bwITZZqUyB9s96Ki69DGIYdmFYfq85iLua5Pj/xTMbyO728MJPKToVlfGPlM0w4swCslUBO5AgPbsYwjJOnHcGi+7lav73xo7EbDkobpUyAzSb2lKbQrFSvSWrOTMHF/gb+MvNg527LXICWY76EBjzlIR4KnYNH4fPDzQEJDc14vMz1EYdaJeEbpkacdw7moYOq1AsAAn22LsKpCSOo11QIrKX82fqaNf19+VXGsDV+q3njsMmHhTkRk1N+wN8y0+Qzze2roNj4lEClieY7vU8szPE/2mffZ70YbVPZBekB7whJWiw3j6ND5XLw==
  template:
    metadata:
      creationTimestamp: null
      name: searxng-secrets
      namespace: searxng
    type: Opaque
