---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudnative-pg-cluster-openwebui
  namespace: openwebui
spec:
  encryptedData:
    password: AgCu5rT1A5u1VhilVQPuDmSSzD99HLM+owqqn/y4rW+nqBjJywuDQSjagFVScrem1B60e0M8d0eAtGvoSR17KfVXRLB7KBpyqQ4bKqtFCofU3sRAB9MOdA5hOB9Fu4YIcdk2gCwgK36Rnvl7sRSpDcWjIBOrLYbirtvSFz3lfLMZCEmLN79bYoURwKZ34wVRs904a09ziYtDIzkwEEbmfH6suKhTuphtKy/5TDxWAvwAZPSYP4iXEwZ/vHDdly5iSXEdEiuHevLgflC4l4CnYwq6AK9DQFiYlTYyhJtqKp3XuP8TBm8894C8BF8rpqZygp65ie2EHkqSNIa1/UanIBI/VSRlwcP/omxyMxB3V/pf7MOvj1ggEpzBsEnMcuY8rELC5j/mmmsq5oUmcAXMh4lL34aBZsBwt2CAqyQt9Bj+ICTimKOkrDg5JCyhMFffByZkgJ2l4Vkj4/K/7IEVMKdRY+S3oRL0O0PZrxZx1t/rGkF7kJ3mfmWid3qCwDAUgQclPlcLDzzbfNwnFo+e5dVLkhVhq9sgTgELZkrO9kdTHVzVjl7GKUYKv/vnFXoPRVx8wbBcJxStojNUDC3I6/vlQpCnFVmdrOvLbMyBzDPpBt0d8VVc0V6CmKztDLYe9xnjCrsA7D/GCZ0B6A5nrpJ0keHWmIRkd8ZBZPhMf9Bup5uCjalO9U8SrNVpmRy0AzPBJqRiBRpQSBDwXH9ZcTwxPIWLoYXYuEfmn+Q8m2yXEg==
    username: AgA8Zgzbqpq+Cz7Rh3rEcTxTGMRzxdfjZzs8D6qRwCno5ZPTlx95ZqUnyCNYdKGAP+mHSNGztwEgvTWdUV3MRYMmjhgEFtLpx0dzcvSvbFTuQEGYk4mMyKeXtvmznoqTSHFOIEyszwhvb/kNL950L1uA/P3UrRuEMK8C/8W8vYSuzIYX8PsEdREVwyx+DKa4SqC07tpe8Hr5rEnqL+VhpwuEu9lDxi+2dA2deOzF0kzWyLSv8i/czakPjfL3mGlWQ2NcXRYKjs5K89PCn5VyXr/x+KpWxLS3fhCoD3JGT06dT1sboqvHIhfpV2OspXDFSdzkSMzVLU8ZN2ltoktcts0wVQsa4ctc6UuzsqXSMX0Mdyvj7Q9DqKnD6loy0ZPnK9hoH7cQ+CXmc/kT06Ti9V1WBC9FY0IJD8cxejxmpAs1gsGQyvOBPkCnB6mwlfo+itJRb+Kc8THuARq+zA2X5VeBZ1Yqe0h1cuZaQZLXFyK8E+qo88P7k3eWBdpvPtrU565+/sctNn3WT4e75nWZZLOWFFukXcBU7ujI24IOt5ocuUoBIdptrmzxFKrLi9cwol4K8Cool1yoYSj+Tf2SiGnsK38zi+m6le+gCXOjkvoKuXASItOqF5kv0NOvFTwtujGgASthkaB/KnGW8hqQFrttyPVzchJeFB8el0kd6bSobmUiSwuT7YU/mLvTHrIKw3pmt/EwOGkH+NY=
  template:
    metadata:
      creationTimestamp: null
      name: cloudnative-pg-cluster-openwebui
      namespace: openwebui
    type: Opaque
