---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: litellm
spec:
  encryptedData:
    CA_VLLM_LOCAL_API_KEY: AgCr9vVAoJi8HImvtuHx+LiFVUDI+2R2BW7qWJt8RAZo0rXUV3st3cc6xvmaFx9d7tbcKr+jZgkjiwRFCcbmukyscFMQbZOp7YEi3o0dj8ynzgyL1wh9bzU/j4VO7MjmUjwbHtnqrizSTPlpdEI2RexDgPotGW6TozZC/vPvkOd/zFE9djKa2AlT/CL1NG2T22ITPSTSd6nHy2aP4Yz5ZzCOICaIAp5SnhVe3CTty0ltJoHaSH5lbMr+S4Vg9jG88gNj0M07ao5o8zPu93TEamj2KD/lPHZRZVrIJONpj3N1XgohFXcxjD4l/CBt7XDgyze+XwZIo1qMPcUfgTZaR1jRuNM/jdFPG2yif5UKCuK00zDNO2bcZhM/6j/oWnOCGF2LLJwuGov8oKtB1KTlNhpUVE3WfaN2xovZW+WR3wxGlODdD3njxPR3wRyMGOKwMeS2SgqpshORZKPM7BB2lO0AxoA5CF9TN/X/1/x3KBJHFhoMCE108dw0kmBAhkN2KtfErfHzK66K1bKXYu3GUvp++hnGML3l2fENBMkUGj0ew6pxjrkv4KTJqpzfq4qCl9vPAm3P6thJOSEGSBOLf7C3xMsvW9k0dHYjG0nyxcAxJ4JEy+NOcfbbJS/v6yVhFbMKBxFSFjJ68ndRRKOpXOuS3lzwkJbqbLQKfjJecu/JLKvIc+ggGWFDqapCdABuT55PaepqeAPpS50pjXtBKppkCnekLhXnX3qcGEbRUjgacw==
    PROXY_MASTER_KEY: AgBjE/zdefSv4TRrYHmc6lJwHzpDIctqN0FCXlOT2weAznnAhoUcZ0pi7OOnsWetXDcu/TYXeQLPsyUYWKjudL9Uq7UoMs/fcGjGntQPLtwnsuYPKtl8K5ViU+k6q6wR2u9ftaZ+y+6ZSzA9s7B1LGZTEMS9uRa/Go8uEsuP7WY8d/npfAtqHFghaqnJpF16ImRhxlhaXbsJju05oSpTnzXx+v/MmMSxf32aBEbTj8vd9m9cIZeARyfU1Y28VLO1yxuIqVLXE+4kyGB/mT1yMOCmKVQ3loBkd+Nhj+NJBS3YK6j/0lsD1Rrh3RvLnHX/ijILNkdc05F0F4m6uwlA90z9WDnYEgM/X63qlc3wngRTwmlq3pd5soaiwk9ZFmyTSKV5sT8pzWYts9+DF0t2KuOHcvDGBGQdB50wFRi6gGtOOS782IK9cmgTS9Eb+y76oIdiJC9FsGrHgcdsU3ubJDbf9vY9Z5vv0OE21VgNzjWXwKcivf4py6QbYzvGCI+RKfcPjgFuMnCuxTd/ZaV+TVtMFmJNS3hd+iG0kZNEg7KQ00YIroPX7naTS3CCtO68d9ywqqDQ6NVucYiqbRgsTvtR8BXundSyvBN+71cHmfzW18ddKq3CqirEVDRxb988hp1cVIO3Rwj8yPhoBoXlm3c7cPTyDHGZWp0YYS6VQ4ysMhau/azPDH1MLrtcAmtbWJ0q2fgrPuiCBtnIwwJLa23We8sctOOGHMa+GYIaaLmECZT+2w==
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: litellm
    type: Opaque
